language: python
sudo: false
cache: pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
install:
  - pip install tox
script:
  - tox -v
deploy:
  provider: pypi
  user: TimofeyKukushkin
  password:
    secure: Ef0InfZNyCsMJywYPUDkuC+HJuFqJd0ltlL8gl0ve+Grh7NgoWCQQVt3o4gKsZ+pvI1n7UXkMmXyvgfT+tQCei4zX7VYcLRdyX8U0GjHmRFaTtElSQccpXMemuPqJj3q2gh0kTAUC7ndc27NhIgxD6HLLAAzfMjXl24kWBZ9xNRxDyJbexguntYUPpM9AJmQLoFBfOVKml7YrsS/dlQrwL2/xPzugC7ufjY13o8Ixtl/p5hVW257A4oxY3LbRKOW/C5hcf1jbSugX1/hY+P1UAx+e3bqTSHDGzczCsdtGBFesFujzQeMm1Tuo+UhczJyGODt3lClnFeHOIl8Heb/ygLCEydde88EiRhuahJ8ceprPNimxiEnzya8mn5fCtjUfBVcca192LkiZ/hfEdmFg2XtINcThR64I13s/zGcX+4uNh2DTIXnbB07LyfVMW1swY/IJby5O2zqlczhQ8PEyLzkb+BUcSJElDTvqFuxGsUmcmlkc+9VR4lAIXCcnmj7e4Z2gPhrpJpbGtjb3SKDgqlCDL7HXBWEnKnaEBo5jf0BjHdvLccwPRUPDVGVZ8TXowz97xsdZzz7FQT4eTUfuRmil8JSL6fbcGhUi0tJo4L+VdNPwNdSyYVsLnOqrArcSLLdC1bGfPtSE17iDV4znJTv9BIywdCpqXUoVXM/yhQ=
  on:
    repo: tkukushkin/pytest-simple-settings
    branch: master
    tags: true
  distributions: sdist bdist_wheel
